#!/bin/bash
chown -R root:root /usr/bin/codegen
chmod -R 777 /usr/bin/codegen

if [ -f "/usr/lib/systemd/system/codegen.service" ]; then
    rm -rf /usr/lib/systemd/system/codegen.service 2>/dev/null || true
    systemctl disable codegen.service 2>/dev/null || true
    systemctl stop codegen.service 2>/dev/null || true
    systemctl daemon-reload 2>/dev/null || true
fi

cat <<EOF > /etc/systemd/system/codegen.service
[Unit]
Description=Code generator - cli tool

[Service]
Type=simple
WorkingDirectory=/usr/bin
ExecStart=/usr/bin/codegen
Restart=always
RestartSec=10
SyslogIdentifier=codegen
KillSignal=SIGINT
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable codegen.service
systemctl restart codegen.service
